import {
  spfOne,
  spfTwo,
  spfThree,
  spfFour,
  bestSellerOne,
  bestSellerTwo,
  bestSellerThree,
  bestSellerFour,
  newArrOne,
  newArrTwo,
  newArrThree,
  newArrFour,
} from "../assets/images/index";

// =================== NavBarList Start here ====================
export const navBarList = [
  {
    _id: 1001,
    title: "Home",
    link: "/",
  },
  {
    _id: 1002,
    title: "Shop",
    link: "/shop",
  },
  {
    _id: 1003,
    title: "About",
    link: "/about",
  },
  {
    _id: 1004,
    title: "Contact",
    link: "/contact",
  },
  {
    _id: 1005,
    title: "Journal",
    link: "/journal",
  },
];
// =================== NavBarList End here ======================

// =================== Special Offer data Start here ============
export const SplOfferData = [
  {
    _id: "201",
    img: spfOne,
    productName: "Cap for Boys",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    cat: "Accessories",
    brand: "Shoppers Home",
    des: "Ergonomic street style cap made with 100% breathable cotton for everyday comfort.",
  },
  {
    _id: "202",
    img: newArrFour,
    productName: "Tea Table",
    price: "180.00",
    color: "Gray",
    badge: true,
    cat: "Home appliances",
    brand: "Hoichoi",
    des: "Minimalist Scandinavian design tea table with reinforced wooden legs.",
  },
  {
    _id: "203",
    img: spfThree,
    productName: "Headphones",
    price: "25.00",
    color: "Mixed",
    badge: true,
    cat: "Electronics",
    brand: "Apple",
    des: "High-fidelity stereo headphones featuring passive noise cancellation.",
  },
  {
    _id: "204",
    img: spfFour,
    productName: "Sun glasses",
    price: "220.00",
    color: "Black",
    badge: true,
    cat: "Accessories",
    brand: "Ultron",
    des: "UV400 protective polarized sunglasses with lightweight titanium alloy frame.",
  },
];
// =================== Special Offer data End here ==============

// =================== PaginationItems Start here ===============
export const paginationItems = [
  {
    _id: 1001,
    img: spfOne,
    productName: "Cap for Boys",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    cat: "Accessories",
    brand: "Shoppers Home",
    rating: 4.8,
    des: "Premium streetwear cotton cap with adjustable metal buckle and ventilated eyelets.",
  },
  {
    _id: 1002,
    img: spfTwo,
    productName: "Tea Table",
    price: "180.00",
    color: "Gray",
    badge: true,
    cat: "Home appliances",
    brand: "Hoichoi",
    rating: 4.6,
    des: "Modern minimalist living room accent table with water-resistant matte finish.",
  },
  {
    _id: 1003,
    img: spfThree,
    productName: "Headphones",
    price: "25.00",
    color: "Mixed",
    badge: true,
    cat: "Electronics",
    brand: "Apple",
    rating: 4.9,
    des: "Crystal-clear acoustic audio headphones with plush memory foam ear cushions.",
  },
  {
    _id: 1004,
    img: spfFour,
    productName: "Sun glasses",
    price: "220.00",
    color: "Black",
    badge: true,
    cat: "Accessories",
    brand: "Ultron",
    rating: 4.7,
    des: "Unisex polarized luxury eyewear with scratch-resistant anti-glare lenses.",
  },
  {
    _id: 1005,
    img: bestSellerOne,
    productName: "Flower Base",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    cat: "Home appliances",
    brand: "Unknown",
    rating: 4.5,
    des: "Handcrafted ceramic decorative vase designed for modern aesthetic living spaces.",
  },
  {
    _id: 1006,
    img: bestSellerTwo,
    productName: "New Backpack",
    price: "180.00",
    color: "Gray",
    badge: false,
    cat: "Bags",
    brand: "Shoppers Home",
    rating: 4.9,
    des: "Water-repellent commuter backpack featuring a padded 15.6-inch laptop compartment.",
  },
  {
    _id: 1007,
    img: bestSellerThree,
    productName: "Household materials",
    price: "25.00",
    color: "Mixed",
    badge: true,
    cat: "Home appliances",
    brand: "Hoichoi",
    rating: 4.4,
    des: "Multipurpose eco-friendly household essentials organizer set.",
  },
  {
    _id: 1008,
    img: bestSellerFour,
    productName: "Travel Bag",
    price: "220.00",
    color: "Black",
    badge: false,
    cat: "Bags",
    brand: "Ultron",
    rating: 4.8,
    des: "Heavy-duty TSA-approved weekender duffel bag with isolated shoe compartment.",
  },
  {
    _id: 1009,
    img: newArrOne,
    productName: "Round Table Clock",
    price: "44.00",
    color: "Black",
    badge: true,
    cat: "Gadgets",
    brand: "Apple",
    rating: 4.6,
    des: "Silent non-ticking analog desk clock with glowing night indices.",
  },
  {
    _id: 1010,
    img: newArrTwo,
    productName: "Smart Watch",
    price: "250.00",
    color: "Black",
    badge: true,
    cat: "Electronics",
    brand: "Apple",
    rating: 5.0,
    des: "Next-gen fitness tracker with continuous heart rate monitoring and AMOLED display.",
  },
  {
    _id: 1011,
    img: newArrThree,
    productName: "cloth Basket",
    price: "80.00",
    color: "Mixed",
    badge: true,
    cat: "Home appliances",
    brand: "Unknown",
    rating: 4.3,
    des: "Collapsible woven cotton laundry hamper with sturdy leather handles.",
  },
  {
    _id: 1012,
    img: newArrFour,
    productName: "Funny toys for babies",
    price: "60.00",
    color: "Mixed",
    badge: false,
    cat: "Gadgets",
    brand: "Hoichoi",
    rating: 4.7,
    des: "BPA-free sensory development activity toy set for infants and toddlers.",
  },
  {
    _id: 1013,
    img: spfOne,
    productName: "Urban Hoodie",
    price: "75.00",
    color: "Blue",
    badge: true,
    cat: "Clothes",
    brand: "Shoppers Home",
    rating: 4.8,
    des: "Heavyweight fleece pullover hoodie with relaxed drop-shoulder fit.",
  },
  {
    _id: 1014,
    img: spfTwo,
    productName: "Minimalist Desk Lamp",
    price: "45.00",
    color: "Green",
    badge: false,
    cat: "Gadgets",
    brand: "Ultron",
    rating: 4.5,
    des: "Dimmable LED architect desk lamp with wireless smartphone charging pad.",
  },
  {
    _id: 1015,
    img: spfThree,
    productName: "Wireless Earbuds Pro",
    price: "129.00",
    color: "Blank and White",
    badge: true,
    cat: "Electronics",
    brand: "Apple",
    rating: 4.9,
    des: "Active noise canceling earbuds with spatial audio and 32-hour total battery life.",
  },
  {
    _id: 1016,
    img: spfFour,
    productName: "Leather Wallet",
    price: "49.00",
    color: "Black",
    badge: false,
    cat: "Accessories",
    brand: "Shoppers Home",
    rating: 4.7,
    des: "Genuine full-grain leather bifold wallet with RFID blocking technology.",
  },
  {
    _id: 1017,
    img: bestSellerOne,
    productName: "Ceramic Coffee Mug",
    price: "18.00",
    color: "Yellow",
    badge: false,
    cat: "Home appliances",
    brand: "Unknown",
    rating: 4.6,
    des: "Matte ceramic 400ml coffee mug with insulated wooden lid and spoon.",
  },
  {
    _id: 1018,
    img: bestSellerTwo,
    productName: "Canvas Tote Bag",
    price: "32.00",
    color: "Gray",
    badge: true,
    cat: "Bags",
    brand: "Hoichoi",
    rating: 4.4,
    des: "Eco-friendly heavy organic cotton tote with reinforced handles.",
  },
  {
    _id: 1019,
    img: bestSellerThree,
    productName: "Aromatherapy Diffuser",
    price: "39.00",
    color: "Green",
    badge: true,
    cat: "Gadgets",
    brand: "Ultron",
    rating: 4.8,
    des: "Ultrasonic essential oil diffuser with ambient 7-color LED lighting.",
  },
  {
    _id: 1020,
    img: bestSellerFour,
    productName: "Duffle Gym Bag",
    price: "95.00",
    color: "Red",
    badge: true,
    cat: "Bags",
    brand: "Shoppers Home",
    rating: 4.7,
    des: "Compact water-resistant sports duffle with ventilated shoe compartment.",
  },
];
// =================== PaginationItems End here =================
